image:
  - Visual Studio 2017

platform:
  - x86

configuration:
  - Debug
  - Release

install:
  - cinst strawberryperl

build_script:
  - cmd: set PATH=%PATH%;C:\Strawberry\perl\bin
  - cmd: cd Dependencies
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cmd: openssl-build
  - cmd: cd ..
  - cmd: premake vs2017
  - cmd: msbuild Build\P4Win.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal